warning[W09003]: unused assignment
  ┌─ tests/custom_rules/multiplication_overflow.move:9:13
  │
9 │         let a: u64 = 1_000_000_000_000_000;
  │             ^ Unused assignment for variable 'a'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_a')
  │
  = This warning can be suppressed with '#[allow(unused_assignment)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09003]: unused assignment
   ┌─ tests/custom_rules/multiplication_overflow.move:10:13
   │
10 │         let b: u64 = 2_000_000_000_000_000;
   │             ^ Unused assignment for variable 'b'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_b')
   │
   = This warning can be suppressed with '#[allow(unused_assignment)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W08001]: Potential overflow detected in multiplication operation
   ┌─ tests/custom_rules/multiplication_overflow.move:11:39
   │
11 │         let _ = 1_000_000_000_000_000 * 2_000_000_000_000_000; // Should trigger a warning
   │                                       ^ Potential overflow detected in multiplication operation
   │
   = This warning can be suppressed with '#[allow(lint(multiplication_overflow))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

