warning[Lint W00001]: Function has too many parameters, which may hinder readability and maintainability.
   ┌─ tests/linter/too_many_arguments.move:9:82
   │  
 9 │       public fun badFunction(_a: u64, _b: u64, _c: u64, _d: u64, _e: u64, _f: u64) {
   │ ╭──────────────────────────────────────────────────────────────────────────────────^
10 │ │         // Function body
11 │ │     }
   │ ╰─────^ Function 'badFunction' has too many parameters (6). Consider refactoring to improve readability.

